version: '3.7'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "6901:5432"